
# --- Backend ---
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = true;

# --- Shadows ---
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;

# --- Rounded Corners ---
corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'""class_g = 'i3-frame'"
];

# --- Transparency/Opacity ---
inactive-opacity = 0.9;
active-opacity = 1.0;
frame-opacity = 0.8;
inactive-opacity-override = false;
focus-exclude = [ "class_g = 'Cairo-clock'" ];

# --- Blur ---
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 5;
blur-background-exclude = [
  "window_type = 'dock'""window_type = 'desktop'"
];

# --- Fading ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;
