#!/bin/bash
# Run the server profile end-to-end on a clean Debian 13.
#
# Links only: package installation takes many minutes and is covered by
# actually using the box. What this proves is that on a machine with nothing
# on it, bootstrap.sh server produces resolvable symlinks and a login shell
# with the right environment.
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

command -v docker >/dev/null 2>&1 || {
  echo "docker is required for this test" >&2
  exit 1
}

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# Export exactly what's committed. This is deliberately not `cp -r`:
# copying the live working tree would drag in .git and the gitignored
# .superpowers/ scratch directory, and would silently let an uncommitted
# file pass the test even though a fresh checkout on a real box wouldn't
# have it.
#
# That means a dirty working tree tests stale (last-commit) state without
# saying so, so make that loud rather than silent.
dirty="$(git -C "$DOTFILES" status --porcelain)"
if [ -n "$dirty" ]; then
  echo "WARNING: testing committed HEAD; working tree has uncommitted" >&2
  echo "changes that will NOT be tested:" >&2
  echo "$dirty" >&2
fi

mkdir -p "$WORKDIR/repo"
git -C "$DOTFILES" archive HEAD | tar -x -C "$WORKDIR/repo"

cat >"$WORKDIR/container-setup.sh" <<'CONTAINER'
set -euo pipefail

apt-get update -qq
apt-get install -y -qq git tmux coreutils >/dev/null

useradd -m -s /bin/bash jkurtz
mkdir -p /home/jkurtz/wd
cp -r /src/repo /home/jkurtz/wd/dotfiles
chown -R jkurtz:jkurtz /home/jkurtz

su - jkurtz -c 'bash /src/user-check.sh'
CONTAINER

cat >"$WORKDIR/user-check.sh" <<'USER'
set -euo pipefail
cd ~/wd/dotfiles

fail() { echo "FAIL: $1" >&2; exit 1; }

# 1. bootstrap succeeds
./setup/bootstrap.sh server || fail "bootstrap.sh server exited non-zero"

# 2. every symlink we created resolves
for link in ~/.profile ~/.profile.local ~/.bash_aliases ~/.gitconfig \
  ~/.tmux.conf ~/.local/bin/clip ~/.config/nvim/init.lua \
  ~/.config/nvim/lua/plugins/blink.lua; do
  [ -L "$link" ] || fail "$link is not a symlink"
  [ -e "$link" ] || fail "$link points at a nonexistent target"
done

# 3. BROWSER=echo reaches a login shell
got=$(bash -lc 'printf "%s" "$BROWSER"') ||
  fail "login shell errored while evaluating BROWSER"
[ "$got" = "echo" ] || fail "BROWSER is '$got', expected 'echo'"

# 4. no agent present -> no SSH_AUTH_SOCK, and no error
got=$(bash -lc 'printf "%s" "${SSH_AUTH_SOCK:-}"') ||
  fail "login shell errored while evaluating SSH_AUTH_SOCK"
[ -z "$got" ] || fail "SSH_AUTH_SOCK is '$got' with no agent running"

# 5. a UTF-8 locale is exported
# Note: this only checks that profile.server's export logic produces a
# UTF-8-looking value. The locale itself is generated by
# server-packages.sh, which this test deliberately skips (links only), so
# this does not prove a working, generated UTF-8 locale on the box.
got=$(bash -lc 'printf "%s" "$LANG"') ||
  fail "login shell errored while evaluating LANG"
case "$got" in
*UTF-8 | *utf8 | *UTF8) ;;
*) fail "LANG is '$got', expected a UTF-8 locale" ;;
esac

# 6. tmux accepts the config and reports set-clipboard on
tmux -f ~/.tmux.conf -L ci new-session -d
got=$(tmux -L ci show -gv set-clipboard)
tmux -L ci kill-server
[ "$got" = "on" ] || fail "tmux set-clipboard is '$got', expected 'on'"

# 7. clip emits the right bytes in both tmux states
ESC=$(printf '\033')
BEL=$(printf '\a')
printf 'hello' | env -u WAYLAND_DISPLAY -u TMUX CLIP_TTY=/tmp/bare ~/.local/bin/clip
expected="${ESC}]52;c;aGVsbG8=${BEL}"
[ "$(cat /tmp/bare)" = "$expected" ] || fail "clip emitted the wrong bare OSC 52"

printf 'hello' | env -u WAYLAND_DISPLAY TMUX=fake CLIP_TTY=/tmp/wrapped ~/.local/bin/clip
expected="${ESC}Ptmux;${ESC}${ESC}]52;c;aGVsbG8=${BEL}${ESC}\\"
[ "$(cat /tmp/wrapped)" = "$expected" ] ||
  fail "clip emitted the wrong tmux-wrapped OSC 52"

# 8. no sway config was created
for p in ~/.config/sway ~/.config/foot ~/.local/bin/swaycwd; do
  [ -e "$p" ] && fail "server profile created $p"
done

echo "server profile: all container checks passed"
USER

docker run --rm -i \
  -v "$WORKDIR:/src:ro" \
  debian:13 bash /src/container-setup.sh
